---
language: ruby
cache: bundler
rvm:
  - 2.4.9
  - 2.5.8
  - 2.6.6
  - 2.6.3
  - 2.7.1
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler:1.17.3
script:
  - bundle exec rspec --order rand
